version: "3.9"
services:
  api:
    build: ./images/api
    image: mohamedmankouchi/api:latest
    environment:
      NODE_ENV:
      PG_CONNECTION_STRING:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_HOST: db
      POSTGRES_USER:
    ports:
      - 80:3000
    volumes:
      - ./images/api/src:/usr/app/src
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.0
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test", "-d", "test"]
      interval: 5s
      timeout: 4s
      retries: 10
      start_period: 10s
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_HOST_AUTH_METHOD:
    volumes:
      - ./_volumes/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
